SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/CalcoloRimborso/Calcola.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Models;

namespace SociFilarmonicaApp
{
    public class CalcolaModel : PageModel
    {
        private readonly FilarmonicaContext _context;

        public CalcolaModel(FilarmonicaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public CalcoloRimborsoVM DatiCalcolo { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var socio = await _context.Soci
                .Include(x => x.DatiAuto)
                .FirstOrDefaultAsync(x => x.ID == id);

            if (socio == null || socio.DatiAutoID == null)
            {
                return NotFound();
            }

            DatiCalcolo = new CalcoloRimborsoVM()
            {
                SocioID = socio.ID,
                Cognome = socio.Cognome,
                Nome = socio.Nome,
                Carburante = socio.DatiAuto.Carburante,
                DescrizioneMacchina = socio.DescrizioneMacchina,
                Distanza = 0,
                InfoAutoID = socio.DatiAutoID.Value,
                RimborsoKm = socio.DatiAuto.RimborsoKm,
                TargaMacchina = socio.TargaMacchina,
                TipoAuto = socio.DatiAuto.TipoAuto,
                ListaProve = new List<DateTime> { DateTime.Now },
                AltriCosti = new List<CalcoloRimborsoAltriCostiVM> { new CalcoloRimborsoAltriCostiVM() }
            };
            return Page();
        }

        public IActionResult OnPostAddDataProva()
        {
            DatiCalcolo.ListaProve.Add(DateTime.Now);
            return Page();
        }
        public IActionResult OnPostRemoveDataProva(int index)
        {
            if(index >= 0 && index < DatiCalcolo.ListaProve.Count)
            {
                DatiCalcolo.ListaProve.RemoveAt(index);
            }
            return Page();
        }

        public IActionResult OnPostAddAltroCosto()
        {
            DatiCalcolo.AltriCosti.Add(new CalcoloRimborsoAltriCostiVM());
            return Page();
        }
        public IActionResult OnPostRemoveAltroCosto(int index)
        {
            if (index >= 0 && index < DatiCalcolo.AltriCosti.Count)
            {
                DatiCalcolo.AltriCosti.RemoveAt(index);
            }
            return Page();
        }

        public IActionResult OnPostCalcolatrice()
        {
            //calcola il totale
            var totale = DatiCalcolo.Calcola();
            DatiCalcolo.TotaleReale = totale;
            return Page();
        }
        public IActionResult OnPost()
        {
            //calcola il totale
            //todo: salva
            return Page();
        }
        
        public IActionResult OnPostGeneraExcel()
        {
            //TODO: stampa excel
            return Page();
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Data.DbModels;
using SociFilarmonicaApp.Models;

namespace SociFilarmonicaApp.Pages.Soci
{
    public class CreateModel : TipologiePageModel
    {
        private readonly FilarmonicaContext _context;

        public CreateModel(FilarmonicaContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            PopulateDropDownLists(_context);
            return Page();
        }

        [BindProperty]
        public SocioVm Socio { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.

        //The SetValues method sets the values of this object by reading values from another PropertyValues object. 
        //SetValues uses property name matching. The view model type doesn't need to be related to the model type, 
        //it just needs to have properties that match.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                var entry = _context.Add(new Socio());
                
                entry.CurrentValues.SetValues(Socio);

                await _context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }
            catch (DbUpdateException ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                PopulateDropDownLists(_context, Socio.TipologiaSocioID);
                return Page();
            }
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Data.DbModels;

namespace SociFilarmonicaApp.Pages.Soci
{
    public class DeleteModel : PageModel
    {
        private readonly FilarmonicaContext _context;

        public DeleteModel(FilarmonicaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Socio Socio { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            Socio = await _context.Soci.AsNoTracking().FirstOrDefaultAsync(m => m.ID == id);

            if (Socio == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ErrorMessage = "Delete failed. Try again";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Socio = await _context.Soci.FindAsync(id);

            if (Socio == null)
                return NotFound();


            try
            {
                Socio.Annullato = true;
                if(await TryUpdateModelAsync(Socio, "socio", s => s.Annullato))
                {
                    await _context.SaveChangesAsync();
                }
                return RedirectToPage("./Index");
            }
            catch (DbUpdateException ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
                return RedirectToAction("./Delete",
                                     new { id, saveChangesError = true });
            }
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Mappings;
using SociFilarmonicaApp.Data.DbModels;
using SociFilarmonicaApp.Models;

namespace SociFilarmonicaApp.Pages.Soci
{
    public class DetailsModel : PageModel
    {
        private readonly Data.FilarmonicaContext _context;

        public DetailsModel(Data.FilarmonicaContext context)
        {
            _context = context;
        }

        public SocioVm Socio { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dbSocio = await _context.Soci
                .Include(x => x.Tipologia)
                .Include(x => x.DatiAuto)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (dbSocio == null)
                return NotFound();

            Socio = dbSocio.ToSocioVm();
            
            return Page();
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Mappings;
using SociFilarmonicaApp.Models;
using SociFilarmonicaApp.Data;

namespace SociFilarmonicaApp.Pages.Soci
{
    public class EditModel : TipologiePageModel
    {
        private readonly FilarmonicaContext _context;

        public EditModel(FilarmonicaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public SocioVm Socio { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dbSocio = await _context.Soci.FirstOrDefaultAsync(m => m.ID == id);

            if (dbSocio == null)
            {
                return NotFound();
            }

            Socio = dbSocio.ToSocioVm();

            PopulateDropDownLists(_context);
            return Page();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(int id)
        {
            if (!ModelState.IsValid)
            {
                PopulateDropDownLists(_context, Socio.TipologiaSocioID, Socio.DatiAutoID);
                return Page();
            }

            var socioDaAggiornare = await _context.Soci.FindAsync(id);
            socioDaAggiornare.DataUltimaModifica = DateTime.Now;

            _context.Entry(socioDaAggiornare).CurrentValues.SetValues(Socio);

            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }

        private bool SocioExists(int id)
        {
            return _context.Soci.Any(e => e.ID == id);
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Data.DbModels;

namespace SociFilarmonicaApp.Pages.Soci
{
    public class IndexModel : PageModel
    {
        private readonly FilarmonicaContext _context;

        public IndexModel(FilarmonicaContext context)
        {
            _context = context;
        }

        public string NomeSort { get; set; }
        public string CognomeSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }

        public PaginatedList<Models.SocioVm> Soci { get;set; }

        public async Task OnGetAsync(string sortOrder, string currentFilter, string searchString, int? pageIndex)
        {
            CurrentSort = sortOrder;
            NomeSort = string.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";
            CognomeSort = sortOrder == "Cognome" ? "Cognome_desc" : "Cognome";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            CurrentFilter = searchString;

            IQueryable<Socio> sociIQ = _context.Soci
                .Where(s => !s.Annullato);

            if (!string.IsNullOrEmpty(searchString))
            {
                sociIQ = sociIQ.Where(x => x.Nome.ToUpper().Contains(searchString.ToUpper()) 
                || x.Cognome.ToUpper().Contains(searchString.ToUpper()));
            }

            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "Nome";
            }

            

            bool descending = false;
            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }

            //dynamic linq: use EF.Property method to specify the name of the property as a string
            if (descending)
            {
                sociIQ = sociIQ.OrderByDescending(e => EF.Property<object>(e, sortOrder));
            }
            else
            {
                sociIQ = sociIQ.OrderBy(e => EF.Property<object>(e, sortOrder));
            }

            int pageSize = 10;
            var sociVmIQ = sociIQ.Select(x => new Models.SocioVm
            {
                NumeroSocio = x.NumeroSocio,
                Cognome = x.Cognome,
                ID = x.ID,
                Nome = x.Nome,
                TipologiaSocioID = x.TipologiaSocioID,
                TipologiaSocioDesc = x.Tipologia.Descrizione,
                PrivacyFirmata = x.PrivacyFirmata,
                DatiAutoID = x.DatiAutoID
            });

            Soci = await PaginatedList<Models.SocioVm>.CreateAsync(sociVmIQ.AsNoTracking(), pageIndex ?? 1, pageSize);
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Riepilogo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Models;

namespace SociFilarmonicaApp.Pages
{
    public class RiepilogoModel : PageModel
    {
        private readonly FilarmonicaContext _context;

        public RiepilogoModel(FilarmonicaContext context)
        {
            _context = context;
        }

        public IList<RiepilogoSociVM> SociPerTipologia { get; set; }
        public async Task OnGetAsync()
        {
            var query = _context.TipologiaSoci
                .Select(x => new RiepilogoSociVM 
                {
                    TipoSocio = x.Descrizione,
                    NumSoci = x.SociDiCategoria.Count()
                });

            SociPerTipologia = await query.AsNoTracking().ToListAsync();
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Rimborsi/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Data.DbModels;

namespace SociFilarmonicaApp.Pages.StoricoRimborsi
{
    public class DeleteModel : PageModel
    {
        private readonly SociFilarmonicaApp.Data.FilarmonicaContext _context;

        public DeleteModel(SociFilarmonicaApp.Data.FilarmonicaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public RimborsoKm RimborsoKm { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RimborsoKm = await _context.RimborsoKm.FirstOrDefaultAsync(m => m.ID == id);

            if (RimborsoKm == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RimborsoKm = await _context.RimborsoKm.FindAsync(id);

            if (RimborsoKm != null)
            {
                _context.RimborsoKm.Remove(RimborsoKm);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/Rimborsi/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SociFilarmonicaApp.Data;
using SociFilarmonicaApp.Data.DbModels;
using SociFilarmonicaApp.Pages.Soci.Rimborsi;

namespace SociFilarmonicaApp.Pages.StoricoRimborsi
{
    public class DetailsModel : ExportRimborsoPageModel
    {
        protected readonly FilarmonicaContext _context;
        private readonly IWebHostEnvironment _env;
        public DetailsModel(IWebHostEnvironment env, FilarmonicaContext context)
        {
            _context = context;
            _env = env;
        }

        public RimborsoKm RimborsoKm { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            var ana = await _context.GetAnagrafica();
            AttachExcelExportAction(_env, ana);

            if (id == null)
            {
                return NotFound();
            }
            //todo: togli questo e visualizza i DatiCalcolo
            RimborsoKm = await _context.RimborsoKm.FirstOrDefaultAsync(m => m.ID == id);

            if (RimborsoKm == null)
            {
                return NotFound();
            }
            await GetExisting(id.Value, _context);
            return Page();
        }
    }
}

SociFilarmonicaApp/SociFilarmonicaApp/Pages/Soci/CalcoloRimborso/Calcola.cshtml
@page
@model SociFilarmonicaApp.CalcolaModel
@{
    ViewData["Title"] = "Calcola";
}

<h1>Calcola il rimborso</h1>
<h2 class="text-muted">@Model.DatiCalcolo.Nome @Model.DatiCalcolo.Cognome</h2>

<hr />
<p><span class="fa fa-info"></span> Aggiungi la lista prove a cui ha partecipato, eventuali altri costi. Premi il pulsante "Calcola" per avere un'anteprima del rimborso spesa. Premi il tasto "???" per salvare e creare il rimborso spesa.</p>
<hr />

<form method="post" asp-route="./Calcola">
    @*Cose che devo ripassare al backend per riaverle nella view*@
    @Html.HiddenFor(model => model.DatiCalcolo.SocioID)
    @Html.HiddenFor(model => model.DatiCalcolo.Nome)
    @Html.HiddenFor(model => model.DatiCalcolo.Cognome)
    @Html.HiddenFor(model => model.DatiCalcolo.InfoAutoID)
    @Html.HiddenFor(model => model.DatiCalcolo.TipoAuto)
    @Html.HiddenFor(model => model.DatiCalcolo.Carburante)
    @Html.HiddenFor(model => model.DatiCalcolo.DescrizioneMacchina)
    @Html.HiddenFor(model => model.DatiCalcolo.TargaMacchina)
    <div class="form-row">
        <div class="col-md-6 pr-3">
            <h6>Lista prove</h6>
            <div class="form-row">
                <div class="form-group col-11">
                    <input asp-for="DatiCalcolo.ListaProve[0]" type="date" class="form-control" />
                    <span asp-validation-for="DatiCalcolo.ListaProve[0]" class="text-danger"></span>
                </div>
            </div>

            @for (int i = 1; i < Model.DatiCalcolo.ListaProve.Count; i++)
            {
                <div class="form-row">
                    <div class="form-group col-11">
                        <input asp-for="DatiCalcolo.ListaProve[i]" type="date" class="form-control" />
                        <span asp-validation-for="DatiCalcolo.ListaProve[i]" class="text-danger"></span>
                    </div>
                    <div class="form-group col-1">
                        <button type="submit" asp-page-handler="RemoveDataProva" asp-route-index="@i" class="btn btn-danger"><i class="fa fa-times"></i></button>
                    </div>
                </div>
            }
            <div class="form-row">
                <div class="form-group col">
                    <button type="submit" asp-page-handler="AddDataProva" class="btn btn-secondary float-right"><i class="fa fa-plus"></i></button>
                </div>
            </div>
            <hr />
            <h6>Altri costi (opzionale)</h6>
            <div class="form-row border-bottom m-1">
                <div class="form-group col-md-6">
                    <label asp-for="DatiCalcolo.AltriCosti[0].Descrizione" class="control-label"></label>
                    <input asp-for="DatiCalcolo.AltriCosti[0].Descrizione" class="form-control" />
                    <span asp-validation-for="DatiCalcolo.AltriCosti[0].Descrizione" class="text-danger"></span>
                </div>
                <div class="form-group col-md-5">
                    <label asp-for="DatiCalcolo.AltriCosti[0].Costo" class="control-label"></label>
                    <input asp-for="DatiCalcolo.AltriCosti[0].Costo" class="form-control" />
                    <span asp-validation-for="DatiCalcolo.AltriCosti[0].Costo" class="text-danger"></span>
                </div>
            </div>
            @for (int i = 1; i < Model.DatiCalcolo.AltriCosti.Count; i++)
            {
                <div class="form-row border-bottom m-1">
                    <div class="form-group col-md-6">
                        <label asp-for="DatiCalcolo.AltriCosti[i].Descrizione" class="control-label"></label>
                        <input asp-for="DatiCalcolo.AltriCosti[i].Descrizione" class="form-control" />
                        <span asp-validation-for="DatiCalcolo.AltriCosti[i].Descrizione" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-5">
                        <label asp-for="DatiCalcolo.AltriCosti[i].Costo" class="control-label"></label>
                        <input asp-for="DatiCalcolo.AltriCosti[i].Costo" class="form-control" />
                        <span asp-validation-for="DatiCalcolo.AltriCosti[i].Costo" class="text-danger"></span>
                    </div>
                    <div class="form-group col-1">
                        <button type="submit" asp-page-handler="RemoveAltroCosto" asp-route-index="@i" class="btn btn-danger"><i class="fa fa-times"></i></button>
                    </div>
                </div>
            }
            <div class="form-row">
                <div class="form-group col">
                    <button type="submit" asp-page-handler="AddAltroCosto" class="btn btn-secondary float-right"><i class="fa fa-plus"></i></button>
                </div>
            </div>
        </div>
        <div class="col-md-6 border-left pr-2">

            <p>@Html.DisplayFor(model => model.DatiCalcolo.TipoAuto) - @Html.DisplayFor(model => model.DatiCalcolo.Carburante)</p>
            <p>@Html.DisplayFor(model => model.DatiCalcolo.DescrizioneMacchina), targa @Html.DisplayFor(model => model.DatiCalcolo.TargaMacchina)</p>
            <div class="form-group">
                <label asp-for="DatiCalcolo.RimborsoKm" class="control-label"></label>
                <input asp-for="DatiCalcolo.RimborsoKm" class="form-control" />
                <span asp-validation-for="DatiCalcolo.RimborsoKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatiCalcolo.Distanza" class="control-label"></label>
                <input asp-for="DatiCalcolo.Distanza" class="form-control" />
                <span asp-validation-for="DatiCalcolo.Distanza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatiCalcolo.TotaleReale" class="control-label"></label>
                <div class="form-control">@Html.DisplayFor(model => model.DatiCalcolo.TotaleReale)</div>
                <span asp-validation-for="DatiCalcolo.TotaleReale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatiCalcolo.TotaleDovuto" class="control-label"></label>
                <input asp-for="DatiCalcolo.TotaleDovuto" class="form-control" />
                <span asp-validation-for="DatiCalcolo.TotaleDovuto" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <button type="submit" asp-page-handler="Calcolatrice" class="btn btn-secondary float-right"><i class="fa fa-calculator"></i> Calcola </button>
                </div>
            </div>
        </div>
    </div>
</form>